global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'storage-space-api'
    static_configs:
      - targets: ['api:5000']  # API service from docker-compose

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # If you add a node-exporter to docker-compose